// <auto-generated />
namespace SocialPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Morefriendrequestfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Morefriendrequestfields));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161545121_More-friendrequest-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
