// <auto-generated />
namespace SocialPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfriendrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfriendrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161429167_add-friendrequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
