// <auto-generated />
namespace SocialPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfirstname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfirstname));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161326129_add-firstname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
